Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,35 +4,89 @@ on:
       - '**'
 
 jobs:
+  docker-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Docker compose config
+        run: docker compose config
+      - name: Verify Dockerfile
+        run: |
+          DOCKERFILE=Dockerfile
+          if [[ ! -f "$DOCKERFILE" ]]; then
+            echo "❌ Dockerfile not found!"
+            exit 1
+          fi
+
+          STAGE_COUNT=$(grep -c '^FROM' "$DOCKERFILE")
+          echo "✅ Found $STAGE_COUNT stages in the Dockerfile."
+          if [[ $STAGE_COUNT -lt 2 ]]; then
+            echo "❌ Dockerfile must have at least 2 stages (multi-stage build required)."
+            exit 1
+          fi
+
+          if ! grep -q '^FROM python:3.11-buster' "$DOCKERFILE"; then
+            echo "❌ Base image is not 'python:3.11-buster'"
+            exit 1
+          else
+            echo "✅ Base image is 'python:3.11-buster'"
+          fi
+
+          if ! grep -q '^WORKDIR /app' "$DOCKERFILE"; then
+            echo "❌ WORKDIR is not set to '/app'"
+            exit 1
+          else
+            echo "✅ WORKDIR is set to '/app'"
+          fi
+
+  integration-test:
+    timeout-minutes: 10
+    name: integration tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Docker compose up
+        run: docker compose up -d --wait
+      - name: Integration tests
+        run: |
+          ./tests/api_tests.sh
+      - name: Docker compose down
+        run: docker compose down
+
   deploy:
     runs-on: ubuntu-latest
-
+    needs:
+      - integration-test
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-      - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v1
+      - name: Authenticate to GCP
+        uses: google-github-actions/auth@v2
         with:
-          project_id: attendencetracker-280595272990
-          #service_account_key: ${{ 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 }}
-          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
+          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
 
-      - name: Configure Docker to use gcloud
-        run: gcloud auth configure-docker
+      - name: Configure Docker
+        run: gcloud auth configure-docker us-central1-docker.pkg.dev
 
-      - name: Build Docker image
-        run: |
-          docker build -t us-central1-docker.pkg.dev/attendencetracker-280595272990/attendencetracker/app:latest .
+      - name: Setup Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          platforms: linux/amd64,linux/arm64
 
-      - name: Push Docker image to Artifact Registry
-        run: |
-          docker push us-central1-docker.pkg.dev/attendencetracker-280595272990/attendencetracker/app:latest
+      - name: Build and Push Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          context: ./
+          file: ./Dockerfile
+          push: true
+          tags: us-central1-docker.pkg.dev/attendencetracker-280595272990/docker-image/app:v1
 
       - name: Deploy to Cloud Run
         run: |
           gcloud run deploy attendencetracker \
-            --image us-central1-docker.pkg.dev/attendencetracker-280595272990/attendencetracker/app:latest \
+            --image us-central1-docker.pkg.dev/attendencetracker-280595272990/docker-image/app:v1 \
             --platform managed \
             --region us-central1 \
             --allow-unauthenticated
